name: LWS Space
favicon: null
layout_spectrum: 0.88665
typography_spectrum: 0.20165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b0b0b0'
    - '#ebece7'
    - '#f46755'
    - '#1d1d1d'
    - '#98473c'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
