name: LWS Space
favicon: null
layout_spectrum: 0.5247233882546425
typography_spectrum: 0.39790080883540213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7570891377981752
  lightness: 0.23520273412577808
  saturation: 0.0019667467568069696
  rhythmicContrast: 0.7550496917683631
purpose: []
